/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.rj.exercicio;

import br.senac.rj.exercicio.gui.JFrameApoliceConsultar;
import br.senac.rj.exercicio.gui.JFrameSeguradoListar;
import br.senac.rj.exercicio.gui.JFrameSeguradoIncluir;
import br.senac.rj.exercicio.gui.JFrameApoliceIncluir;
import br.senac.rj.exercicio.gui.JFrameSeguradoConsultar;
import javax.swing.JFrame;

/**
 *
 * @author Senac
 */
public class ApoliceMain extends javax.swing.JFrame {

    JFrame jFrameSeguradoConsultar;
    JFrame jFrameSeguradoListar;
    JFrame jFrameApoliceIncluir;
    JFrame jFrameSeguradoIncluir;
    JFrame jFrameApoliceConsultar;

    
    /**
     * Creates new form ApoliceMain
     */
    public ApoliceMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemApoliceNova = new javax.swing.JMenuItem();
        jMenuApoliceConsultar = new javax.swing.JMenu();
        jMenuItemApoliceConsutlarPorNumero = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemSeguradoIncluir = new javax.swing.JMenuItem();
        jMenuSeguradoConsultar = new javax.swing.JMenu();
        jMenuItemSeguradoConsultarPorCpf = new javax.swing.JMenuItem();
        jMenuItemSeguradoConsultarPorMatricula = new javax.swing.JMenuItem();
        jMenuItemSeguradoListar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SApo - Sistema de Apólices");
        setLocationByPlatform(true);
        setName("framePrincipal"); // NOI18N

        jMenu1.setText("Apólice");

        jMenuItemApoliceNova.setText("Nova");
        jMenuItemApoliceNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApoliceNovaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemApoliceNova);

        jMenuApoliceConsultar.setText("Consultar");

        jMenuItemApoliceConsutlarPorNumero.setText("Por Número");
        jMenuItemApoliceConsutlarPorNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApoliceConsutlarPorNumeroActionPerformed(evt);
            }
        });
        jMenuApoliceConsultar.add(jMenuItemApoliceConsutlarPorNumero);

        jMenuItem2.setText("Por Segurado");
        jMenuApoliceConsultar.add(jMenuItem2);

        jMenu1.add(jMenuApoliceConsultar);
        jMenu1.add(jSeparator1);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Segurado");

        jMenuItemSeguradoIncluir.setText("Novo");
        jMenuItemSeguradoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSeguradoIncluirActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSeguradoIncluir);

        jMenuSeguradoConsultar.setText("Consultar");

        jMenuItemSeguradoConsultarPorCpf.setText("Por CPF");
        jMenuSeguradoConsultar.add(jMenuItemSeguradoConsultarPorCpf);

        jMenuItemSeguradoConsultarPorMatricula.setText("Por Matrícula");
        jMenuItemSeguradoConsultarPorMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSeguradoConsultarPorMatriculaActionPerformed(evt);
            }
        });
        jMenuSeguradoConsultar.add(jMenuItemSeguradoConsultarPorMatricula);

        jMenu2.add(jMenuSeguradoConsultar);

        jMenuItemSeguradoListar.setText("Listar");
        jMenuItemSeguradoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSeguradoListarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSeguradoListar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSeguradoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSeguradoIncluirActionPerformed
        if (jFrameSeguradoIncluir == null) {
            jFrameSeguradoIncluir = new JFrameSeguradoIncluir();
        }
        jFrameSeguradoIncluir.setVisible(true);
    }//GEN-LAST:event_jMenuItemSeguradoIncluirActionPerformed

    private void jMenuItemApoliceConsutlarPorNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApoliceConsutlarPorNumeroActionPerformed
        if (jFrameApoliceConsultar == null) {
            jFrameApoliceConsultar = new JFrameApoliceConsultar();
        }
        jFrameApoliceConsultar.setVisible(true);
    }//GEN-LAST:event_jMenuItemApoliceConsutlarPorNumeroActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemSeguradoConsultarPorMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSeguradoConsultarPorMatriculaActionPerformed
        if (jFrameSeguradoConsultar == null) {
            jFrameSeguradoConsultar = new JFrameSeguradoConsultar();
        }
        jFrameSeguradoConsultar.setVisible(true);
    }//GEN-LAST:event_jMenuItemSeguradoConsultarPorMatriculaActionPerformed

    private void jMenuItemSeguradoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSeguradoListarActionPerformed
        if (jFrameSeguradoListar == null) {
            jFrameSeguradoListar = new JFrameSeguradoListar();
        }
        jFrameSeguradoListar.setVisible(true);
    }//GEN-LAST:event_jMenuItemSeguradoListarActionPerformed

    private void jMenuItemApoliceNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApoliceNovaActionPerformed
        if (jFrameApoliceIncluir == null) {
            jFrameApoliceIncluir = new JFrameApoliceIncluir();
        }
        jFrameApoliceIncluir.setVisible(true);
    }//GEN-LAST:event_jMenuItemApoliceNovaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApoliceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApoliceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApoliceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApoliceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApoliceMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuApoliceConsultar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemApoliceConsutlarPorNumero;
    private javax.swing.JMenuItem jMenuItemApoliceNova;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSeguradoConsultarPorCpf;
    private javax.swing.JMenuItem jMenuItemSeguradoConsultarPorMatricula;
    private javax.swing.JMenuItem jMenuItemSeguradoIncluir;
    private javax.swing.JMenuItem jMenuItemSeguradoListar;
    private javax.swing.JMenu jMenuSeguradoConsultar;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
